### ISSUE TITLE
Cloning repo on Windows 10

### ISSUE THREAD

**Issue by Hajdukson** [academind/flutter-complete-guide-course-resources#1]
Cloning attempt on Windows maschine thorws the following erorr from this [Issue](https://github.com/desktop/desktop/issues/6323). Installing [Linux subsystem for Windows](https://learn.microsoft.com/en-us/windows/wsl/install) fix the error. But it might be great to fix it to avoid unnecessary disappointment :smile:

**Comment by camposFabio** [comment]
The problem is with the ":" on the names. Windows does not accept that
error: invalid path 'Code Snapshots/02 Flutter & Dart Basics I/04 Practice Solution: Styling Text/lib/main.dart'
fatal: unable to checkout working tree
