### ISSUE TITLE
assets.zip isn't downloading

### ISSUE THREAD

**Issue by Shrarn** [academind/flutter-complete-guide-course-resources#7]
flutter-complete-guide-course-resources/Lecture Attachments/03 Flutter and Dart Basics/assets.zip isn't opening and downloading.

**Comment by CanIChangeThisLaterPlease** [comment]
Try cloning the whole repository then moving the assets zip command being:
git clone https://github.com/academind/flutter-complete-guide-course-resources.git
paste this into a path you would like to have the repository in then find the specific file you are looking for
(flutter-complete-guide-course-resources/Lecture Attachments/03 Flutter and Dart Basics/assets.zip)

**Comment by Shrarn** [comment]
That did work!! Thank you.
